### ISSUE TITLE
How to use OrgaJS with Next?

### ISSUE THREAD

**Issue by ThomasFKJorna** [orgapp/orgajs#119]
Hi! I am one of the people working on [org-roam-ui](https://github.com/org-roam/org-roam-ui). One of the things we would like to incorporate in the near future is displaying and possibly editing org files, ideally using something faster/more featureful than ox-html. Orga seems ideal for this purpose, however, I've been having some (read, a lot 😅) of trouble even getting a basic example to work. 

We are using Next and TypeScript, which should not be an obstacle per se, but I have been getting a lot of import errors.

To test, you could check out https://github.com/org-roam/org-roam-ui/tree/orga.

Thanks for making Orga! I'm looking forward to collaborate in the future :)

# What happens
When opening `localhost:3000/orga`, I get the following errors

## missing date-format
```sh
info  - ready on http://localhost:3000
event - build page: /orga
wait  - compiling...
error - ./node_modules/date-fns-tz/esm/format/index.js:1:0
Module not found: Can't resolve 'date-fns/esm/format'
null
Error: Cannot find module 'date-fns/format'
Require stack:
- node_modules/date-fns-tz/format/index.js
- node_modules/date-fns-tz/index.js
- node_modules/orga/dist/timestamp.js
- node_modules/orga/dist/index.js
- node_modules/@orgajs/reorg-parse/dist/index.js
- node_modules/@orgajs/reorg/dist/index.js
- build/server/pages/orga.js
- node_modules/next/dist/next-server/server/require.js
- node_modules/next/dist/next-server/server/load-components.js
- node_modules/next/dist/next-server/server/api-utils.js
- node_modules/next/dist/next-server/server/next-server.js
- node_modules/next/dist/server/next.js
- node_modules/next/dist/server/lib/start-server.js
- node_modules/next/dist/cli/next-dev.js
- node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.mod._resolveFilename (node_modules/next/dist/build/webpack/require-hook.js:4:1855)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/node_modules/date-fns-tz/format/index.js:8:38)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'node_modules/date-fns-tz/format/index.js',
    'node_modules/date-fns-tz/index.js',
    'node_modules/orga/dist/timestamp.js',
    'node_modules/orga/dist/index.js',
    'node_modules/@orgajs/reorg-parse/dist/index.js',
    'node_modules/@orgajs/reorg/dist/index.js',
    'build/server/pages/orga.js',
    'node_modules/next/dist/next-server/server/require.js',
    'node_modules/next/dist/next-server/server/load-components.js',
    'node_modules/next/dist/next-server/server/api-utils.js',
    'node_modules/next/dist/next-server/server/next-server.js',
    'node_modules/next/dist/server/next.js',
    'node_modules/next/dist/server/lib/start-server.js',
    'node_modules/next/dist/cli/next-dev.js',
    'node_modules/next/dist/bin/next'
  ]
}
```
## ESM errors
# Files
## org.tsx
I have a file called `orga.tsx`, which looks like
```tsx
import React from "react"
import stream from "unified-stream"
/* import * as reorg from "@orgajs/reorg" */
import reorg from '@orgajs/reorg'
import toRehype from '@orgajs/reorg-rehype'
import toEstree from '@orgajs/rehype-estree'
import toJsx from '@orgajs/estree-jsx'

export default function TestPage() {
    const processor = reorg()
        .use(toRehype)
        .use(toEstree, { skipExport: true, skipImport: true })
        .use(toJsx)
    const jsx = processor.processSync("* Headline")
    return (
        <div>
            {jsx}
        </div>
    )
}
```

## next.config.js 
(I removed the `pageExtensions` as that made it fail even more.
```tsx
const fs = require('fs')

const withPlugins = require('next-compose-plugins')
const withPWA = require('next-pwa')
const withOrga = require('@orgajs/next')

const d3packages = fs.readdirSync('node_modules').filter((name) => name.startsWith('d3-'))
const withTM = require('next-transpile-modules')(d3packages)

module.exports = withPlugins([withTM, withPWA, withOrga], {
  distDir: 'build',
  pwa: {
    dest: 'build',
  },
})
```

## tsconfig.json
```tsx
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "ESNext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "allowSyntheticDefaultImports": true
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
```

**Comment by ThomasFKJorna** [comment]
Fantastic, I have been able to get most of everything I want to work!!

I will be playing around with it sometime in the future and will let you know if I run up against any major bugs. I'll also add to the documentation where I can, as I got a lot of useful info from the Playground, but that is not referenced anywhere yet. Let me know if you have anything specific you think would be useful to add!

Thank you!
